# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
encoding: utf-8

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "newsid"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "publish"
        field:
          element: "text"
          label: "Published Date"
          value: "CURRENT_DATETIME"
      - name: "expire"
        field:
          element: "text"
          label: "Expiration Date"
          value: "CURRENT_DATETIME"
      - name: "system"
        field:
          element: "checkbox"
          label: "System Message"
          help: "currently not used"
          value: false
      - name: "feature"
        field:
          element: "number"
          label: "Featured Item"
          help: ""
          value: 0
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          help: ""
          options:
            - name: "AOC"
              value: "aoc"
            - name: "Supreme Court"
              value: "supreme"
      - name: "news"
        field:
          element: "hidden"
          value: true
      - name: "carousel"
        field:
          element: "hidden"
          value: 'false'
    _posts/carousel:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "newsid"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "publish"
        field:
          element: "text"
          label: "Published Date"
          value: "CURRENT_DATETIME"
      - name: "expire"
        field:
          element: "text"
          label: "Expiration Date"
          value: "CURRENT_DATETIME"
      - name: "system"
        field:
          element: "checkbox"
          label: "System Message"
          help: "currently not used"
          value: false
      - name: "feature"
        field:
          element: "number"
          label: "Featured Item"
          help: ""
          value: 0
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          help: ""
          options:
            - name: "AOC"
              value: "aoc"
            - name: "Supreme Court"
              value: "supreme"
      - name: "news"
        field:
          element: "checkbox"
          label: "Show in news feed"
          value: true
      - name: "carousel"
        field:
          element: "hidden"
          value: true
      - name: "carousel_expire"
        field:
          element: "text"
          label: "Carousel Expiration"
          value: "CURRENT_DATETIME"
